### ISSUE TITLE
Identification of all participants with Rainbow table

### ISSUE THREAD

**Issue by LazyDev2k** [rarimo/passport-zk-circuits#9]
Let `F(x)` be a hash function that is used to anonymize participants, where `x` is a data from the bio-metric passport.

Your security model is based on the assumption that if an attacker E knows value `y` where `y=F(x)`, then attacker E will be unable to deduce `y` because of properties of `F`.

However you oppose an attacker E that has access to information about all valid values of `x` (data from each valid passport is known to E). So the attacker can just take all valid values of `x` (x1, x2... xN), compute `F(x)` for each of them (even if there 140 millions, that's not a problem), and then just search for value that corresponds for a `y` value of a certain voter.

So if the attacker E has access to the data in all that was used to determine if a certain user can vote, and access to all passport data, then the attacker is able to identify each voter.

It is impossible to make a voting system were:
- The voting criteria is based on data known to possible attackers (your case!)
- Voting results are fully verifiable by each participant (that is what you claim)
- Voting is fully anonymous (that is what you claim)
- Duplicate voting is prohibited (that is what you claim)

See also: https://en.wikipedia.org/wiki/Rainbow_table

PS: I recommend to delete this issue after acknowledging the problem

**Comment by sborkin** [comment]
Isn't the current timestamp used to create the hash? Then the attacker cannot create identical hashes to compare it in the votes DB

**Comment by LazyDev2k** [comment]
> Isn't the current timestamp used to create the hash? Then the attacker cannot create identical hashes to compare it in the votes DB

Not current timestamp but current date. So all hashes for single day are same. It's not a problem to compute hashes for 100-1000 different days.

**Comment by 1KitCat1** [comment]
We acknowledge the potential risk of a dictionary attack on our system. To counteract this, we have implemented the use of a blinding factor on the side of the identity provider. Simplified, this approach involves creating a document nullifier by applying the Poseidon hash function to a combination of the passport hash and a blinding factor. This method effectively obstructs an attacker's ability to identify users through a dictionary attack by obfuscating the direct relationship between the passport information and its representation in our system.
We are also working on applying Active authentication to deterministically generate the document nullifier. 
With active authentication, the chip securely stores a private key within a secure module, which is never disclosed. We anticipate that this level of security is so robust that not even government entities could gain access to it.

Also, we are not using "current date" to create a document nullifier (hash).
